site_name: RC-PCR CLASSIFIER
repo_name: jordycoolen/RC-PCR_CLASSIFIER
repo_url: https://github.com/jordycoolen/RC-PCR_CLASSIFIER
edit_uri: ""

theme:
  name: material
  language: en

# standard config settings
  features:
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.instant
      - toc.integrate
      - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Switch light mode
  font:
      text: Roboto
      code: Roboto Mono
  plugins:
      - search
      - awesome-pages

nav:
  - Home: index.md

# extensions
markdown_extensions:
    - meta
    - markdown.extensions.admonition
    - markdown.extensions.attr_list
    - markdown.extensions.codehilite:
        guess_lang: false
    - markdown.extensions.def_list
    - markdown.extensions.footnotes
    - markdown.extensions.meta
    - markdown.extensions.toc:
        permalink: true
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink:
        repo_url_shorthand: true
        social_url_shorthand: true
        user: Jordy Coolen
        repo: RC-PCR CLASSIFIER
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.snippets:
        check_paths: true
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

extra:
  version:
    provider: mike